name: Build/run tgov

on:
  push:
    branches: [ "main", "diarize-flow" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: "1.3.2"
      POETRY_VENV: "/opt/poetry-venv"
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_DEFAULT_REGION: us-east-2

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev ffmpeg
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        python3 -m venv "${POETRY_VENV}"
        $POETRY_VENV/bin/pip install -U pip setuptools
        $POETRY_VENV/bin/pip install "poetry==${POETRY_VERSION}"
        /opt/poetry-venv/bin/poetry config virtualenvs.create false
        /opt/poetry-venv/bin/poetry install
        /opt/poetry-venv/bin/poetry env info

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::480103772849:role/GitHubCFTRole
        aws-region: us-east-2

    - name: Run Diarization
      run: |
        /opt/poetry-venv/bin/python -m flows.transcribe_meetings
